### ISSUE TITLE
Change minimum Python version to 3.8

### ISSUE THREAD

**Issue by roskakori** [pygraz/old-django-website#35]
## Goals

- [x] References to Python 2.7 constructs are removed. In particular:
  - `from __future__` imports
  - `from six` imports
  - `unicode`
- [x] The pre-commit ensures modern Python is used consistently.
  ```yaml
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.3
    hooks:
      - id: pyupgrade
        args: ["--py38-plus"]
  ```

## Design decision

We use Python 3.8 because this is the one available on the server.
