### ISSUE TITLE
Clean up formatting of HTML templates

### ISSUE THREAD

**Issue by roskakori** [pygraz/old-django-website#36]
## Goals

- [ ] HTML templates are formatted consistently

## Implementation notes

Use [djhtml](https://github.com/rtts/djhtml) with pre-commit:

```yaml
  - repo: https://github.com/rtts/djhtml
    rev: v1.5.2
    hooks:
      - id: djhtml
        # Indent only HTML files in template directories
        files: .*/templates/.*\.html$
```
